apiVersion: v1
kind: Pod
metadata:
  name: curl-with-ambassador

spec:
  containers:
    - name: main
      image: curlimages/curl
      command:
        - sleep
      args:
        - "9999999"
    - name: ambassador
      image: krishnaramachandran1973/kubectl-proxy
