apiVersion: v1
kind: Pod
metadata:
  name: fortune
spec:
  containers:
    - name: html-generator
      image: krishnaramachandran1973/fortune
      volumeMounts:
        - mountPath: /var/htdocs
          name: html
      imagePullPolicy: IfNotPresent

    - name: web-server
      image: nginx:alpine
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
  restartPolicy: Always

  volumes:
    - name: html
      emptyDir: {}
