apiVersion: v1
kind: ConfigMap
metadata:
  name: kubia-config
data:
  mysql_db: kubia
  mysql_username: root
  mysql_password: root
  mysql_server: kubia-mysql


---

apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  type: LoadBalancer
  selector:
    app: kubia
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: krishnaramachandran1973/kubia:2.0
        env:
          - name: MYSQL_DB
            valueFrom:
                configMapKeyRef:
                  name: kubia-config
                  key: mysql_db
          - name: MYSQL_USERNAME
            valueFrom:
                configMapKeyRef:
                  name: kubia-config
                  key: mysql_username
          - name: MYSQL_PASSWORD
            valueFrom:
                configMapKeyRef:
                  name: kubia-config
                  key: mysql_password
          - name: MYSQL_SERVER
            valueFrom:
                configMapKeyRef:
                  name: kubia-config
                  key: mysql_server                        
        ports:
        - containerPort: 8080