apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  containers:
    - name: kubia-manual
      image: krishnaramachandran1973/kubia:unhealthy
      livenessProbe:
        httpGet:
          port: 8080
          path: /alive
        initialDelaySeconds: 10
      ports:
        - containerPort: 8080
