apiVersion: v1
kind: Pod
metadata:
  name: curl-custom-sa
spec:
  serviceAccountName: foo
  containers:
    - name: main
      image: curlimages/curl
      command:
        - sleep
      args:
        - "9999999"
    - name: ambassador
      image: luksa/kubectl-proxy
