management:
  endpoints:
    enabled-by-default: true
    web:      exposure:        include:        - "*"
spring:  datasource:
    password: ${MYSQL_PASSWORD:root}
    username: ${MYSQL_USERNAME:root}
    url: jdbc:mysql://${MYSQL_SERVER:localhost}:3306/${MYSQL_DB:kubia}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true    