apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod
  labels:
    app: fortune-pod
spec:
  containers:
    - name: fortune-pod
      image: krishnaramachandran1973/fortune:env
      env:
        - name: INTERVAL
          value: "10"
